### PR TITLE
Full tf2 support

### PR DESCRIPTION
**Pull request by Bihaqo**

### CODE REVIEW

**Comment by faysou** [comment]
Hi Alexander, what's the reason for not merging pull requests ?

**Comment by Bihaqo** [comment]
I can't quite make tests to run. I created this issue for the `nose` which
I use for running tests, but they are not actively maintaining the code I
guess: https://github.com/nose-devs/nose/issues/1101

**Comment by faysou** [comment]
Ah ok. I thought that given it's your repository it wouldn't be an issue.

**Comment by faysou** [comment]
Nice work !

**Comment by Bihaqo** [comment]
Thanks :)

**Comment by faysou** [comment]
I wonder if your library will be used by more people at some point because it can be really useful for compressing matrices in neural networks. At least by keeping it up to date we will know.

**Pull request merged**
